version: '3'

services:
  drupal:
    build: .
    image: meljadyn/custom-drupal
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - drupal-data:/var/lib/postgresql/data
